{
 "title": "finnhub dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "BTC trade price",
   "type": "timeseries",
   "description": "BTC trade price",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "select symbol,price, event_time  from trades where symbol = 'BINANCE:BTCUSDT' and event_time>$__timeFrom and event_time<$__timeTo;"
    }
   ]
  },
  {
   "title": "All-time trades count",
   "type": "stat",
   "description": "The total number of trades",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT count(*) as \"Trades count\" FROM trades;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT avg_price as \"Average trade price over the last minute\" FROM minute_trades LIMIT 1;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT total as \"Number of trades over the last minute\" FROM minute_trades LIMIT 1;"
    }
   ]
  },
  {
   "title": "BTC trade volume",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 10 },
   "targets": [
    {
     "target": "SELECT symbol, event_time, volume FROM trades WHERE symbol = 'BINANCE:BTCUSDT' AND event_time>$__timeFrom AND event_time<$__timeTo;"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 10 },
   "targets": [
    {
     "target": "SELECT * FROM minute_trades LIMIT 4;"
    }
   ]
  }
 ]
}